<?php
/**
*font lists
*
*
*/

function lets_define_fontlist(){
$ntl_fontlist=array(
	array("family"=>"Abel","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Abril Fatface","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Aclonica","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Acme","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Actor","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Adamina","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Advent Pro","variants"=>array("300","400","700"),"subsets"=>array("greek","latin","latin-ext")),
		array("family"=>"Aguafina Script","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Aladin","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Aldrich","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Alegreya","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Alegreya SC","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Alex Brush","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Alfa Slab One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Alice","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Alike","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Alike Angular","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Allan","variants"=>array("bold"),"subsets"=>array("latin")),
		array("family"=>"Allerta","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Allerta Stencil","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Allura","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Almendra","variants"=>array("400","400italic","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Almendra SC","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Amaranth","variants"=>array("regular","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Amatic SC","variants"=>array("400","700"),"subsets"=>array("latin")),
		array("family"=>"Amethysta","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Andada","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Andika","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"Angkor","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Annie Use Your Telescope","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Anonymous Pro","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Antic","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Antic Didone","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Antic Slab","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Anton","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Arapey","variants"=>array("400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Arbutus","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Architects Daughter","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Arimo","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Arizonia","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Armata","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Artifika","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Arvo","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Asap","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Asset","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Astloch","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Asul","variants"=>array("400","bold"),"subsets"=>array("latin")),
		array("family"=>"Atomic Age","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Aubrey","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Audiowide","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Average","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Averia Gruesa Libre","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Averia Libre","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Averia Sans Libre","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Averia Serif Libre","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Bad Script","variants"=>array("400"),"subsets"=>array("cyrillic","latin")),
		array("family"=>"Balthazar","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Bangers","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Basic","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Battambang","variants"=>array("regular","bold"),"subsets"=>array("khmer")),
		array("family"=>"Baumans","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Bayon","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Belgrano","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Belleza","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Bentham","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Berkshire Swash","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Bevan","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Bigshot One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Bilbo","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Bilbo Swash Caps","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Bitter","variants"=>array("400","400italic","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Black Ops One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Bokor","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Bonbon","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Boogaloo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Bowlby One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Bowlby One SC","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Brawler","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Bree Serif","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Bubblegum Sans","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Buda","variants"=>array("300"),"subsets"=>array("latin")),
		array("family"=>"Buenard","variants"=>array("400","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Butcherman","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Butterfly Kids","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Cabin","variants"=>array("400","400italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Cabin Condensed","variants"=>array("400","700"),"subsets"=>array("latin")),
		array("family"=>"Cabin Sketch","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Caesar Dressing","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Cagliostro","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Calligraffitti","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Cambo","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Candal","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Cantarell","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Cantata One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Cardo","variants"=>array("regular","400italic","700"),"subsets"=>array("greek","greek-ext","latin","latin-ext")),
		array("family"=>"Carme","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Carter One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Caudex","variants"=>array("400","italic","700","700italic"),"subsets"=>array("greek","greek-ext","latin","latin-ext")),
		array("family"=>"Cedarville Cursive","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Ceviche One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Changa One","variants"=>array("regular","italic"),"subsets"=>array("latin")),
		array("family"=>"Chango","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Chau Philomene One","variants"=>array("400","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Chelsea Market","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Chenla","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Cherry Cream Soda","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Chewy","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Chicle","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Chivo","variants"=>array("400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Coda","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Codystar","variants"=>array("300","400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Comfortaa","variants"=>array("300","400","700"),"subsets"=>array("cyrillic","cyrillic-ext","greek","latin","latin-ext")),
		array("family"=>"Coming Soon","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Concert One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Condiment","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Content","variants"=>array("regular","bold"),"subsets"=>array("khmer")),
		array("family"=>"Contrail One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Convergence","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Cookie","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Copse","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Corben","variants"=>array("400","bold"),"subsets"=>array("latin")),
		array("family"=>"Cousine","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Coustard","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Covered By Your Grace","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Crafty Girls","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Creepster","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Crete Round","variants"=>array("400","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Crimson Text","variants"=>array("regular","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Crushed","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Cuprum","variants"=>array("regular","400italic","700","700italic"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Cutive","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Damion","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Dancing Script","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Dangrek","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Dawning of a New Day","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Days One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Delius","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Delius Swash Caps","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Delius Unicase","variants"=>array("400","700"),"subsets"=>array("latin")),
		array("family"=>"Della Respira","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Devonshire","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Didact Gothic","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Diplomata","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Diplomata SC","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Doppio One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Dorsa","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Dosis","variants"=>array("300","400","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Dr Sugiyama","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Droid Sans","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Droid Sans Mono","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Droid Serif","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Duru Sans","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Dynalight","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"EB Garamond","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext","vietnamese")),
		array("family"=>"Eater","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Economica","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Electrolize","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Emblema One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Emilys Candy","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Engagement","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Enriqueta","variants"=>array("400","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"EricaOne","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Esteban","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Euphoria Script","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ewert","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Exo","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Expletus Sans","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Fanwood Text","variants"=>array("400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Fascinate","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Fascinate Inline","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Federant","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Federo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Felipa","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Fjord One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Flamenco","variants"=>array("300","400"),"subsets"=>array("latin")),
		array("family"=>"Flavors","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Fondamento","variants"=>array("400","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Fontdiner Swanky","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Forum","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"Francois One","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Frederickathe Great","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Fredoka One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Freehand","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Fresca","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Frijole","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"FugazOne","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"GFS Didot","variants"=>array("regular"),"subsets"=>array("greek")),
		array("family"=>"GFS Neohellenic","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("greek")),
		array("family"=>"Galdeano","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Gentium Basic","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Gentium Book Basic","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Geo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Geostar","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Geostar Fill","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Germania One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Give You Glory","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Glass Antiqua","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Glegoo","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Gloria Hallelujah","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Goblin One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Gochi Hand","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Gorditas","variants"=>array("400","bold"),"subsets"=>array("latin")),
		array("family"=>"Goudy Bookletter 1911","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Graduate","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Gravitas One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Great Vibes","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Gruppo","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Gudea","variants"=>array("400","italic","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Habibi","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Hammersmith One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Handlee","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Hanuman","variants"=>array("regular","bold"),"subsets"=>array("khmer")),
		array("family"=>"Happy Monkey","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Henny Penny","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Herr Von Muellerhoff","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Holtwood One SC","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Homemade Apple","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Homenaje","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"IM Fell DW Pica","variants"=>array("regular","italic"),"subsets"=>array("latin")),
		array("family"=>"IM Fell DW Pica SC","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"IM Fell Double Pica","variants"=>array("regular","italic"),"subsets"=>array("latin")),
		array("family"=>"IM Fell Double Pica SC","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"IM Fell English","variants"=>array("regular","italic"),"subsets"=>array("latin")),
		array("family"=>"IM Fell English SC","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"IM Fell French Canon","variants"=>array("regular","italic"),"subsets"=>array("latin")),
		array("family"=>"IM Fell French Canon SC","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"IM Fell Great Primer","variants"=>array("regular","italic"),"subsets"=>array("latin")),
		array("family"=>"IM Fell Great Primer SC","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Iceberg","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Iceland","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Imprima","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Inconsolata","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Inder","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Indie Flower","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Inika","variants"=>array("400","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"IrishG rover","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Istok Web","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"Italiana","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Italianno","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Jim Nightshade","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Jockey One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Jolly Lodger","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Josefin Sans","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Josefin Slab","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Judson","variants"=>array("400","400italic","700"),"subsets"=>array("latin")),
		array("family"=>"Julee","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Junge","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Jura","variants"=>array("300","400"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Just Another Hand","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Just Me Again Down Here","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Kameron","variants"=>array("400","700"),"subsets"=>array("latin")),
		array("family"=>"Karla","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Kaushan Script","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Kelly Slab","variants"=>array("regular"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Kenia","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Khmer","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Knewave","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Kotta One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Koulen","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Kranky","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Kreon","variants"=>array("300","400","700"),"subsets"=>array("latin")),
		array("family"=>"Kristi","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Krona One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"La Belle Aurore","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Lancelot","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Lato","variants"=>array("300","300italic","400","400italic","700","700italic","900","900italic"),"subsets"=>array("latin")),
		array("family"=>"League Script","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Leckerli One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Ledger","variants"=>array("400"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Lekton","variants"=>array("400","italic","700"),"subsets"=>array("latin")),
		array("family"=>"Lemon","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Lilita One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Limelight","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Linden Hill","variants"=>array("400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Lobster","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"Lobster Two","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Londrina Outline","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Londrina Shadow","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Londrina Sketch","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Londrina Solid","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Lora","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Love Ya Like A Sister","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Loved by the King","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Lovers Quarrel","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Luckiest Guy","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Lusitana","variants"=>array("400","bold"),"subsets"=>array("latin")),
		array("family"=>"Lustria","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Macondo","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Macondo Swash Caps","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Magra","variants"=>array("400","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Maiden Orange","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Mako","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Marck Script","variants"=>array("400"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Marko One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Marmelad","variants"=>array("400"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Marvel","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Mate","variants"=>array("400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Mate SC","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Maven Pro","variants"=>array("400","700"),"subsets"=>array("latin")),
		array("family"=>"Meddon","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Medieval Sharp","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Medula One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Megrim","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Merienda One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Merriweather","variants"=>array("300","regular","700"),"subsets"=>array("latin")),
		array("family"=>"Metal","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Metamorphous","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Metrophobic","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Michroma","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Miltonian","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Miltonian Tattoo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Miniver","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Miss Fajardose","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Modern Antiqua","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Molengo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Monofett","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Monoton","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Monsieur La Doulaise","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Montaga","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Montez","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Montserrat","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Moul","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Moulpali","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Mountains of Christmas","variants"=>array("regular","700"),"subsets"=>array("latin")),
		array("family"=>"Mr Bedfort","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Mr Dafoe","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Mr De Haviland","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Mrs Saint Delafield","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Mrs Sheppards","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Muli","variants"=>array("300","300italic","400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Mystery Quest","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Neucha","variants"=>array("regular"),"subsets"=>array("cyrillic","latin")),
		array("family"=>"Neuton","variants"=>array("200","300","regular","italic","700","800"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"News Cycle","variants"=>array("regular","700"),"subsets"=>array("latin")),
		array("family"=>"Niconne","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Nixie One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nobile","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Nokora","variants"=>array("400","700"),"subsets"=>array("khmer")),
		array("family"=>"Norican","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Nosifer","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Nothing You Could Do","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Noticia Text","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext","vietnamese")),
		array("family"=>"Nova Cut","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nova Flat","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nova Mono","variants"=>array("regular"),"subsets"=>array("greek","latin")),
		array("family"=>"Nova Oval","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nova Round","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nova Script","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nova Slim","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Nova Square","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Numans","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Nunito","variants"=>array("300","400","700"),"subsets"=>array("latin")),
		array("family"=>"Odor Mean Chey","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Old Standard TT","variants"=>array("regular","italic","bold"),"subsets"=>array("latin")),
		array("family"=>"Oldenburg","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Oleo Script","variants"=>array("400","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Open Sans","variants"=>array("300","300italic","400","400italic","700","700italic"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext","vietnamese")),
		array("family"=>"Open Sans Condensed","variants"=>array("300","300italic","700"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext","vietnamese")),
		array("family"=>"Orbitron","variants"=>array("400","500","700"),"subsets"=>array("latin")),
		array("family"=>"Original Surfer","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Oswald","variants"=>array("300","regular","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Over the Rainbow","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Overlock","variants"=>array("400","400italic","700","700italic","900","900italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Overlock SC","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ovo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Oxygen","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"PT Mono","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"PT Sans","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"PT Sans Caption","variants"=>array("regular","bold"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"PT Sans Narrow","variants"=>array("regular","bold"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"PT Serif","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("cyrillic","latin")),
		array("family"=>"PT Serif Caption","variants"=>array("regular","italic"),"subsets"=>array("cyrillic","latin")),
		array("family"=>"Pacifico","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Parisienne","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Passero One","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Passion One","variants"=>array("400","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Patrick Hand","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Patua One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Paytone One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Permanent Marker","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Petrona","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Philosopher","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("cyrillic","latin")),
		array("family"=>"Piedra","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Pinyon Script","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Plaster","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Play","variants"=>array("regular","bold"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Playball","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Playfair Display","variants"=>array("regular","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Podkova","variants"=>array("regular","700"),"subsets"=>array("latin")),
		array("family"=>"Poiret One","variants"=>array("400"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Poller One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Poly","variants"=>array("400","400italic"),"subsets"=>array("latin")),
		array("family"=>"Pompiere","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Pontano Sans","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"PortLligat Sans","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"PortLligat Slab","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Prata","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Preahvihear","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Press Start 2P","variants"=>array("400"),"subsets"=>array("cyrillic","greek","latin","latin-ext")),
		array("family"=>"Princess Sofia","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Prociono","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Prosto One","variants"=>array("400"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Puritan","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Quantico","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Quattrocento","variants"=>array("regular","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Quattrocento Sans","variants"=>array("regular","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Questrial","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Quicksand","variants"=>array("300","400","700"),"subsets"=>array("latin")),
		array("family"=>"Qwigley","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Radley","variants"=>array("regular","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Raleway","variants"=>array("100"),"subsets"=>array("latin")),
		array("family"=>"Rammetto One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Rancho","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Rationale","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Redressed","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Reenie Beanie","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Revalia","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ribeye","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ribeye Marrow","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Righteous","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Rochester","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Rock Salt","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Rokkitt","variants"=>array("regular","700"),"subsets"=>array("latin")),
		array("family"=>"Ropa Sans","variants"=>array("400","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Rosario","variants"=>array("regular","italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Rosarivo","variants"=>array("400","italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Rouge Script","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Ruda","variants"=>array("400","bold"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ruge Boogie","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ruluko","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Ruslan Display","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"Russo One","variants"=>array("400"),"subsets"=>array("cyrillic","latin","latin-ext")),
		array("family"=>"Ruthie","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Sail","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Salsa","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Sancreek","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"SansitaOne","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Sarina","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Satisfy","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Schoolbell","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Seaweed Script","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Sevillana","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Shadows Into Light","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Shadows Into Light Two","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Shanti","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Share","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Shojumaru","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Short Stack","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Siemreap","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Sigmar One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Signika","variants"=>array("300","400","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Signika Negative","variants"=>array("300","400","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Simonetta","variants"=>array("400","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Sirin Stencil","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Six Caps","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Slackey","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Smokum","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Smythe","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Snippet","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Sofia","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Sonsie One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Sorts Mill Goudy","variants"=>array("400","400italic"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Special Elite","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Spicy Rice","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Spinnaker","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Spirax","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Squada One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Stardos Stencil","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Stint Ultra Condensed","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Stint Ultra Expanded","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Stoke","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Sue Ellen Francisco","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Sunshiney","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Supermercado One","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Suwannaphum","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Swankyand Moo Moo","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Syncopate","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Tangerine","variants"=>array("regular","bold"),"subsets"=>array("latin")),
		array("family"=>"Taprom","variants"=>array("regular"),"subsets"=>array("khmer")),
		array("family"=>"Telex","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Tenor Sans","variants"=>array("regular"),"subsets"=>array("cyrillic","cyrillic-ext","latin","latin-ext")),
		array("family"=>"The Girl Next Door","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Tienne","variants"=>array("400","700"),"subsets"=>array("latin")),
		array("family"=>"Tinos","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Titan One","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Trade Winds","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Trocchi","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Trochut","variants"=>array("400","italic","bold"),"subsets"=>array("latin")),
		array("family"=>"Trykker","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Tulpen One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Ubuntu","variants"=>array("300","300italic","regular","italic","bold","bolditalic"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Ubuntu Condensed","variants"=>array("400"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Ubuntu Mono","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("cyrillic","cyrillic-ext","greek","greek-ext","latin","latin-ext")),
		array("family"=>"Ultra","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Uncial Antiqua","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"UnifrakturCook","variants"=>array("bold"),"subsets"=>array("latin")),
		array("family"=>"UnifrakturMaguntia","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Unkempt","variants"=>array("regular","700"),"subsets"=>array("latin")),
		array("family"=>"Unlock","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Unna","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"VT323","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Varela","variants"=>array("regular"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Varela Round","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Vast Shadow","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Vibur","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Vidaloka","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Viga","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Voces","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Volkhov","variants"=>array("400","400italic","700","700italic"),"subsets"=>array("latin")),
		array("family"=>"Vollkorn","variants"=>array("regular","italic","bold","bolditalic"),"subsets"=>array("latin")),
		array("family"=>"Voltaire","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Waiting for the Sunrise","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Wallpoet","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Walter Turncoat","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Wellfleet","variants"=>array("400"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Wire One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Yanone Kaffeesatz","variants"=>array("300","400","700"),"subsets"=>array("latin","latin-ext")),
		array("family"=>"Yellowtail","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Yeseva One","variants"=>array("regular"),"subsets"=>array("latin")),
		array("family"=>"Yesteryear","variants"=>array("400"),"subsets"=>array("latin")),
		array("family"=>"Zeyada","variants"=>array("regular"),"subsets"=>array("latin")));


		return apply_filters('lets_define_fontlist',$ntl_fontlist);
}
	

		
	

?>